### ISSUE TITLE
Show current username colour.

### ISSUE THREAD

**Issue by dashed** [vartan/robin-grow#41]
Folks love to brag their colours...

**Comment by matchai** [comment]
User colors are designated with the following snippets:

``` javascript
initialize: function() {
            var e = this.get("name").toLowerCase()
              , t = e.replace(/[^a-z0-9]/g, "") // gets rid of special characters
              , n = parseInt(t, 36) % f; // f = 6
            this.flairClass = "flair-" + n
        },
```

``` css
.robin--flair-class--flair-0 .robin--username{color:#e50000} // red
.robin--flair-class--flair-1 .robin--username{color:#db8e00} // gold/orange
.robin--flair-class--flair-2 .robin--username{color:#ccc100} // yellow
.robin--flair-class--flair-3 .robin--username{color:#02be01} // green
.robin--flair-class--flair-4 .robin--username{color:#0083c7} // blue
.robin--flair-class--flair-5 .robin--username{color:#820080} // purple
.robin--user-class--self .robin--username{color:#222222} // black [for yourself]
.robin--user-class--system .robin--username{color:#a5a4a4}. // gray [for the system]
```

JS taken from https://www.redditstatic.com/robin.en.zk9Y47iW3Fo.js
CSS taken from https://www.redditstatic.com/robin.vav5XXPh1g0.css
